language: node_js
 node_js:
    - "stable"

branches:
    only:
    - master

before_install:

install:

before_script:
  - npm install
  - bower install
  - npm install -g firebase-tools

script:

after_success:  
  - firebase deploy

after_script:

before_deploy:
  - test $TRAVIS_TEST_RESULT = 0
  - gulp build
  - cd public\
deploy:

after_deploy: